// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my Lumina profile",
  description: "Return the signed-in Lumina learner's profile: display name, XP, streak, current difficulty, and totals.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb(ctx);
    const [{ data: profile }, { data: memory }] = await Promise.all([
      client.from("profiles").select("display_name, xp, streak").eq("user_id", ctx.getUserId()).maybeSingle(),
      client.from("student_memory").select("current_difficulty, total_quizzes, total_correct, total_questions, last_activity_at").eq("user_id", ctx.getUserId()).maybeSingle()
    ]);
    const out = { profile, memory };
    return { content: [{ type: "text", text: JSON.stringify(out) }], structuredContent: out };
  }
});

// src/lib/mcp/tools/list-topics.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_topics_default = defineTool2({
  name: "list_topics",
  title: "List learning topics",
  description: "List available Lumina learning topics, optionally filtered by a case-insensitive search string.",
  inputSchema: {
    search: z.string().trim().max(120).nullable().describe("Optional search term matched against topic title/category."),
    limit: z.number().int().min(1).max(50).nullable().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb2(ctx).from("topics").select("id, title, category, description, difficulty").limit(limit ?? 20);
    if (search) q = q.or(`title.ilike.%${search}%,category.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { topics: data ?? [] } };
  }
});

// src/lib/mcp/tools/recent-quiz-attempts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var recent_quiz_attempts_default = defineTool3({
  name: "list_recent_quiz_attempts",
  title: "Recent quiz attempts",
  description: "List the signed-in learner's most recent quiz attempts with score, total, XP earned, and topic id.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).nullable().describe("Max attempts to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("quiz_attempts").select("id, topic_id, score, total, xp_earned, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { attempts: data ?? [] } };
  }
});

// src/lib/mcp/tools/recent-chat.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var recent_chat_default = defineTool4({
  name: "list_recent_chat_messages",
  title: "Recent tutor chat messages",
  description: "List the signed-in learner's most recent Lumina tutor chat messages (both user and assistant), newest last.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).nullable().describe("Max messages to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb4(ctx).from("chat_messages").select("id, role, content, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).reverse();
    return { content: [{ type: "text", text: JSON.stringify(rows) }], structuredContent: { messages: rows } };
  }
});

// src/lib/mcp/tools/save-note.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var save_note_default = defineTool5({
  name: "save_tutor_note",
  title: "Save a note to tutor chat",
  description: "Append a note (as an assistant message) into the signed-in learner's Lumina tutor chat history.",
  inputSchema: {
    content: z4.string().trim().min(1).max(4e3).describe("Markdown note content to save into chat history.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ content }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb5(ctx).from("chat_messages").insert({ user_id: ctx.getUserId(), role: "assistant", content }).select("id, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Saved note ${data.id}` }], structuredContent: { note: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "efuddqxrqdfvpzqxiulc";
var mcp_default = defineMcp({
  name: "lumina-mcp",
  title: "Lumina AI Tutor",
  version: "0.1.0",
  instructions: "Tools for Lumina, an AI tutor app. Use these to read the signed-in learner's profile, topics, recent quiz attempts, and tutor chat history, and to append notes to their chat.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_topics_default, recent_quiz_attempts_default, recent_chat_default, save_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
